services:
  mariadb:
    image: mariadb:11.4-noble
    container_name: mariadb
    restart: unless-stopped
    ports:
      - 8281:3306
    volumes:
      - /volume2/docker/mariadb/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
    user: "1026:100"
