services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    ports:
      - "8282:5432"
    volumes:
      - /volume2/docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: default
