services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    network_mode: host
    restart: unless-stopped
    volumes:
      - /volume2/docker/adguardhome/conf:/opt/adguardhome/conf
      - /volume2/docker/adguardhome/data:/opt/adguardhome/work
